# Revered Whistle

- type: loadoutEffectGroup
  id: MasterWhistle
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 54000 #15 hrs

- type: loadout
  id: HeadOfSecurityWhistle
  equipment:
    neck: ADTReveredWhistle
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterWhistle

- type: loadout
  id: HeadofSecurityMantleShoulder
  equipment:
    neck: ClothingNeckMantleHOSShoulder
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS


- type: loadout
  id: HoSPDA
  equipment:
    id: HoSPDA

- type: loadout
  id: ADTSheriffPDA
  equipment:
    id: ADTSheriffPDA
